apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: eap-demo
  namespace: jboss-eap-test-001
spec:
  applicationImage: 'quayecosystem-quay-example-quayio-private-001.apps.okd.thekeunster.local/kelee/custom-eap:v0.1.0'
  replicas: 1
